"""test

Revision ID: 8c3a595b5728
Revises: 
Create Date: 2018-06-13 13:54:22.292529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c3a595b5728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    op.drop_table('city')
    op.drop_table('country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('Id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('countryname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('countrycode', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_comment='国家信息',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('city',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_comment='市级信息',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_info',
    sa.Column('Id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('usertype', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('enabled', mysql.INTEGER(display_width=2), autoincrement=False, nullable=True),
    sa.Column('realname', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('qq', mysql.VARCHAR(length=14), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tel', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_comment='用户信息表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
